"""deleted onupdate from updated_at

Revision ID: 319ff8f3b674
Revises: e7fafd60f885
Create Date: 2026-03-07 13:24:47.624462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ff8f3b674'
down_revision: Union[str, None] = 'e7fafd60f885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
