"""add stats to links

Revision ID: 54bb2dbbfff5
Revises: c9ee58e9cf07
Create Date: 2026-03-06 14:42:28.576034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bb2dbbfff5'
down_revision: Union[str, None] = 'c9ee58e9cf07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('links', sa.Column('is_active', sa.Boolean(), nullable=False))

    op.add_column('links', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE links SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('links', 'is_active', nullable=False)

    op.add_column('links', sa.Column('last_use', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('updated_at', sa.DateTime(), nullable=True))

    op.add_column('links', sa.Column('clicks', sa.Integer(), nullable=True))
    op.execute("UPDATE links SET clicks = 0 WHERE clicks IS NULL")
    op.alter_column('links', 'clicks', nullable=False)

    op.add_column('links', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'expires_at')
    op.drop_column('links', 'clicks')
    op.drop_column('links', 'updated_at')
    op.drop_column('links', 'last_use')
    op.drop_column('links', 'is_active')
    # ### end Alembic commands ###
