"""fixed created_at timezone

Revision ID: a0807a06e0ce
Revises: 319ff8f3b674
Create Date: 2026-03-07 13:33:13.439236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0807a06e0ce'
down_revision: Union[str, None] = '319ff8f3b674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
