"""dates are optional in sqlalchemy

Revision ID: c1e3b33b1431
Revises: a0807a06e0ce
Create Date: 2026-03-09 12:38:47.001583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e3b33b1431'
down_revision: Union[str, None] = 'a0807a06e0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
