"""tzinfo=None in table links

Revision ID: e7fafd60f885
Revises: 54bb2dbbfff5
Create Date: 2026-03-06 16:46:34.551929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fafd60f885'
down_revision: Union[str, None] = '54bb2dbbfff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
